const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {initJSDOM} = require('./test-helpers');
const source = fs.readFileSync(path.resolve(__dirname,'../../part-61-calculator/storage.js'),'utf8');
const tick = () => new Promise(resolve => setTimeout(resolve,20));
function setup(url = 'http://localhost/part-61-calculator/', handler) {
  const h = initJSDOM({domOptions:{url,beforeParse(window){window.CertPathConfig={enabled:true,apiBase:'http://localhost:8787'};window.localStorage.setItem('simply-endorsed:part61-scenario',JSON.stringify({version:1,targets:['commercial-asel'],experience:{total:'999'}}));}}});
  const requests=[];
  h.window.fetch=async(url,options)=>{requests.push({url,options});return handler ? handler(url,options) : {ok:false,status:503,json:async()=>({error:'Unavailable'})};};
  h.window.eval(source);
  return {...h,requests};
}
function contact(h){const form=h.document.getElementById('cp-contact-form');for(const [key,value] of Object.entries({firstName:'Casey',lastName:'Test',email:'casey@example.com',phone:'5025550100'}))form.elements[key].value=value;return form;}
function submit(h,form){form.dispatchEvent(new h.window.Event('submit',{bubbles:true,cancelable:true}));}
(async()=>{
  let h=setup();
  assert.equal(h.document.getElementById('part61CalculatorView').dataset.cpView,'intro');
  assert.equal(h.document.querySelector('[data-select-target][aria-pressed=true]').dataset.selectTarget,'private-asel');
  h.document.querySelector('[data-cp=start]').click();
  assert.equal(h.document.getElementById('part61CalculatorView').dataset.cpView,'calculator');
  h.document.getElementById('part61RandomSampleBtn').click();
  assert.equal(h.document.getElementById('part61CalculatorView').dataset.cpView,'contact');
  assert.equal(h.requests.length,0);
  const f=contact(h); submit(h,f);await tick();
  assert.equal(h.document.getElementById('part61CalculatorView').dataset.cpView,'contact');
  assert.equal(f.elements.firstName.value,'Casey');
  assert.match(h.document.getElementById('cp-message').textContent,/Unavailable/);
  const key=h.requests[0].options.headers['Idempotency-Key'];submit(h,f);await tick();
  assert.equal(h.requests[1].options.headers['Idempotency-Key'],key);
  h.dom.window.close();
  let saved;
  h=setup(undefined,(url,o)=>{const body=JSON.parse(o.body);saved={...body,id:'test-id',token:'test-private-token',revision:1,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};return {ok:true,status:201,json:async()=>saved};});
  h.document.querySelector('[data-cp=start]').click();h.document.getElementById('part61RandomSampleBtn').click();submit(h,contact(h));await tick();
  assert.equal(h.document.getElementById('part61CalculatorView').dataset.cpView,'calculator');
  assert.equal(h.document.querySelector('.part61-workbench').dataset.activeStep,'4');
  assert.match(h.window.location.hash,/plan=test-id/);
  assert.equal(h.window.localStorage.getItem('certpath:saved-plan'),null);
  h.document.querySelector('[data-cp=edit]').click();
  assert.equal(h.document.querySelector('.part61-workbench').dataset.activeStep,'3');
  h.document.getElementById('part61CalculateBtn').click();submit(h,contact(h));await tick();
  assert.equal(h.requests.at(-1).options.method,'PUT');
  assert.equal(JSON.parse(h.requests.at(-1).options.body).revision,1);
  assert.equal(h.requests.at(-1).options.headers.Authorization,'Bearer test-private-token');
  h.dom.window.close();
  h=setup('http://localhost/part-61-calculator/#plan=test-id&key=test-private-token',()=>({ok:true,status:200,json:async()=>saved}));await tick();
  assert.equal(h.document.querySelector('.part61-workbench').dataset.activeStep,'4');
  assert.match(h.document.getElementById('cp-saved-name').textContent,/Casey Test/);
  h.dom.window.close();
  h=setup();
  const malicious=JSON.parse(JSON.stringify(saved));
  malicious.plan.audits[0].summary.rawRequirementSum='<img src=x onerror=alert(1)>';
  malicious.plan.audits[0].summary.estimatedTotalCost='<img src=x onerror=alert(1)>';
  malicious.plan.audits[0].links.push({url:'javascript:alert(1)',label:'Unsafe'});
  h.window.CertPathCalculator.present(malicious);
  assert.equal(h.document.querySelector('#part61Summary img'),null);
  assert.equal(h.document.querySelector('#part61Links a[href^="javascript:"]'),null);
  h.dom.window.close();
  h=setup();h.document.querySelector('[data-cp=inbox]').click();await tick();
  assert.equal(h.requests.length,0);assert.equal(h.document.getElementById('cp-list').textContent,'');
  assert.equal(h.document.getElementById('cp-locked').hidden,false);
  h.dom.window.close();
  h=setup(undefined,(url,o)=>{
    if(url.endsWith('/owner/unlock')) return {ok:true,status:200,json:async()=>({token:'owner-test-token'})};
    if(o.method==='DELETE'||url.endsWith('/owner/logout')) return {ok:true,status:204};
    if(url.includes('/owner/plans?')) return {ok:true,status:200,json:async()=>({items:[saved],nextCursor:null})};
    return {ok:true,status:200,json:async()=>saved};
  });
  h.document.querySelector('[data-cp=inbox]').click();
  h.document.querySelector('[data-cp=unlock]').click();
  const unlock=h.document.getElementById('cp-unlock-form'); unlock.elements.pin.value='123456'; submit(h,unlock); await tick();
  h.document.querySelector('[data-record]').click();await tick();
  assert.ok(h.document.getElementById('part61CalculatorView').classList.contains('cp-owner-view'));
  h.document.querySelector('[data-cp=delete]').click();h.document.querySelector('[data-cp=confirm-delete]').click();await tick();
  assert.equal(h.document.getElementById('cp-message').textContent,'Submission deleted.');
  h.document.querySelector('[data-cp=lock]').click();await tick();
  assert.equal(h.document.getElementById('cp-list').textContent,'');
  assert.equal(h.document.getElementById('cp-contact-form').elements.firstName.value,'');
  h.dom.window.close();
  console.log('PASS: fresh start, contact gate, failure preservation, retry key, save, private reopen, latest-plan update, locked inbox without data fetch');
})().catch(error=>{console.error(error);process.exit(1);});
