#!/usr/bin/env python3
"""Run after sync-avionics; bind offline cache revisions to final shared bytes."""
from pathlib import Path
from hashlib import sha256
import json,re
root=Path(__file__).resolve().parents[1]
shared=['assets/appearance.js','assets/avionics.css','assets/site-nav.js','assets/tactile.js']
buildpath=root/'pilotsolve/BUILD.json'
build=json.loads(buildpath.read_text())
h=sha256()
for rel in build['files']:
 p=root/rel.lstrip('/') if rel.startswith('/') else root/'pilotsolve'/rel
 h.update(rel.encode());h.update(p.read_bytes())
# Fetch-policy changes also require a new cache revision; exclude its own name.
worker_source=(root/'pilotsolve/sw.js').read_text()
h.update(re.sub(r'pilotsolve-site-[a-f0-9]+','pilotsolve-site-VERSION',worker_source).encode())
cache='pilotsolve-site-'+h.hexdigest()[:12]
sw=root/'pilotsolve/sw.js'
sw.write_text(re.sub(r'pilotsolve-site-[a-f0-9]+',cache,sw.read_text()))
build['cache']=cache
buildpath.write_text(json.dumps(build,indent=2)+'\n')
sw=root/'simply-endorsed/sw.js';s=sw.read_text()
s=re.sub(r'  // Shared tactile assets.*?  // End shared tactile assets\n','',s,flags=re.S)
entries='  // Shared tactile assets (generated by refresh-tactile-caches.py)\n'+''.join('  "/'+rel+'?v='+sha256((root/rel).read_bytes()).hexdigest()[:10]+'",\n' for rel in shared)+'  // End shared tactile assets\n'
s=s.replace('const CORE_ASSETS = [\n','const CORE_ASSETS = [\n'+entries)
s=s.replace('.filter((key) => key !== CACHE_NAME)','.filter((key) => key.startsWith("simply-endorsed-") && key !== CACHE_NAME)')
# Version legacy tool styles by bytes just like their HTML references.
for rel in ['assets/tool-system/tool-core.css','assets/tool-system/simply-endorsed.css','assets/tool-system/part61.css']:
 digest=sha256((root/rel).read_bytes()).hexdigest()[:10]
 s=re.sub(r'(/'+re.escape(rel)+r')(?:\?[^"\s]*)?(?=")',lambda m:m.group(1)+'?v='+digest,s)
# Bind the revision to every precached file and the worker policy, excluding
# its own generated name so repeated refreshes are deterministic.
cache_hash=sha256(re.sub(r'const CACHE_NAME = "[^"]+";', 'const CACHE_NAME = "VERSION";',s).encode())
core=re.search(r'const CORE_ASSETS = \[(.*?)\];',s,re.S).group(1)
for url in re.findall(r'"([^"]+)"',core):
 rel=url.split('?',1)[0]
 asset=root/rel.lstrip('/') if rel.startswith('/') else root/'simply-endorsed'/rel
 if asset.is_dir():asset=asset/'index.html'
 cache_hash.update(url.encode());cache_hash.update(asset.read_bytes())
h=cache_hash.hexdigest()[:12]
s=re.sub(r'const CACHE_NAME = "[^"]+";',f'const CACHE_NAME = "simply-endorsed-tactile-{h}";',s)
sw.write_text(s)
print(cache, 'simply-endorsed-tactile-'+h)
# Flight Lesson Guide: version authored data/PDFs and shared dependencies together.
# Its service worker owns only its prefix and explicit allowlist.
guide=root/'flight-lesson-guide'
if (guide/'sw.js').exists():
 worker=guide/'sw.js';source=worker.read_text()
 normalized=re.sub(r"const CACHE_NAME = CACHE_PREFIX \+ '[^']+';", "const CACHE_NAME = CACHE_PREFIX + 'VERSION';", source)
 digest=sha256(normalized.encode())
 files=sorted(p for p in guide.rglob('*') if p.is_file() and p.name!='sw.js' and not p.name.startswith('._'))
 named_shared=['assets/appearance.js','assets/avionics.css','assets/design-system.css','assets/site-nav.js','assets/tactile.js','assets/site-footer.css','assets/site-footer.js','assets/avionics-icons.svg']
 files += [root/rel for rel in named_shared]
 files += [root/'assets/identities/flight-lesson-guide'/name for name in ['logo.png','icon-48.png','icon-192.png','icon-180.png']]
 for file in files:
  if file.exists():digest.update(str(file.relative_to(root)).encode());digest.update(file.read_bytes())
 revision=digest.hexdigest()[:12]
 worker.write_text(re.sub(r"const CACHE_NAME = CACHE_PREFIX \+ '[^']+';", "const CACHE_NAME = CACHE_PREFIX + '"+revision+"';", source))
 print('flight-lesson-guide-'+revision)
