/* FOI Cards content inventory
 * Source: FOI Quick Review, v2.14 (updated Apr. 05, 2026).
 * Every card is traceable to a source page for auditability.
 */
(function () {
  const slug = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  const c = (section, prompt, answer, sourcePage, tags = [], cardType) => ({
    id: `${sourcePage}-${slug(section)}-${slug(prompt)}`,
    section,
    prompt,
    answer,
    sourcePage,
    tags,
    cardType: cardType || (tags.includes('mnemonic') ? 'mnemonic' : tags.includes('procedure') ? 'sequence' : tags.includes('list') ? 'list' : /differ|difference|vs\.?/i.test(prompt) ? 'comparison' : 'definition')
  });

  const baseCards = [
    c('Human behavior', 'What is human behavior?', 'The result of attempts to satisfy certain needs.', 1, ['definition']),
    c('Human behavior', 'What is motivation, and why does it matter?', 'Motivation is the force that causes a person to move toward a goal. It is the greatest influence on learning.', 1, ['definition']),
    c('Human behavior', 'How can motivations vary?', 'They may be positive or negative; tangible or intangible; and obvious or subtle and difficult to identify.', 1, ['list']),
    c('Human behavior', 'What are human needs?', 'The things humans require for normal growth and development.', 1, ['definition']),
    c('Human behavior', 'What is Maslow’s hierarchy of needs, from basic to highest?', '1. Physiological (biological)\n2. Safety and security\n3. Love/belonging (social)\n4. Self-esteem (egoistic)\n5. Self-actualization (self-fulfillment)', 1, ['mnemonic', 'list']),
    c('Human behavior', 'What are defense mechanisms?', 'Subconscious mechanisms that protect individuals against the realities of unpleasant situations.', 1, ['definition']),
    c('Human behavior', 'What does “Dr, Dr, CPR Fast” stand for?', 'Denial, Repression, Displacement, Rationalization, Compensation, Projection, Reaction Formation, Fantasy.', 1, ['mnemonic']),
    c('Human behavior', 'What is denial?', 'Refusing to admit a truth; it is a form of repression.', 1),
    c('Human behavior', 'What is repression?', 'Placing uncomfortable thoughts into inaccessible areas of the mind.', 1),
    c('Human behavior', 'What is displacement?', 'Taking anger out on someone else.', 1),
    c('Human behavior', 'What is rationalization?', 'Justifying unacceptable actions.', 1),
    c('Human behavior', 'What is compensation?', 'Hiding weaknesses by emphasizing strengths elsewhere.', 1),
    c('Human behavior', 'What is projection?', 'Blaming others.', 1),
    c('Human behavior', 'What is reaction formation?', 'Faking a belief opposite to the actual belief.', 1),
    c('Human behavior', 'What is fantasy?', 'Daydreaming.', 1),
    c('Human behavior', 'What emotional reactions can obstruct learning?', 'Anxiety; feelings of unfair treatment; impatience; worry or lack of interest; apathy due to inadequate instruction; and physical discomfort, illness, fatigue, or dehydration.', 1, ['list']),
    c('Human behavior', 'What is stress?', 'The body’s response to demands placed on it.', 1, ['definition']),
    c('Human behavior', 'How do normal individuals react to stress?', 'They become extremely sensitive to their surroundings and respond rapidly—often automatically—within their experience and training.', 1),
    c('Human behavior', 'What are abnormal responses to stress?', 'Severe anger at the instructor or others; inappropriate laughter or singing; marked changes in mood on different lessons; and random or illogical actions.', 1, ['list']),
    c('Human behavior', 'What is anxiety?', 'A reaction to stress that produces a feeling of worry, nervousness, or unease.', 1, ['definition']),
    c('Human behavior', 'What adverse responses can anxiety cause?', 'A hesitancy or inability to act, or an impulse to do something quickly.', 1),
    c('Human behavior', 'How can an instructor counter adverse anxiety responses?', 'Reinforce the learner’s enjoyment of flying; treat fears as a normal reaction instead of ignoring them; and introduce new maneuvers with care.', 1, ['procedure']),
    c('Human behavior', 'What should an instructor do when a learner may have a disqualifying psychological defect?', 'Get a second opinion from another instructor. If both agree, withhold endorsements and recommendations. Report hazardous behavior affecting airman certification to the local FSDO.', 1, ['procedure']),

    c('Learning', 'What is learning theory?', 'A body of principles that explains how people acquire knowledge, skills, and attitudes.', 1, ['definition']),
    c('Learning', 'What are the phases of knowledge acquisition (MUA)?', 'Memorization, Understanding, Application.', 1, ['mnemonic', 'list']),
    c('Learning', 'What does behaviorism say about learning?', 'Learning occurs by having behaviors reinforced or controlled through stimulus and response.', 1, ['definition']),
    c('Learning', 'How do classical and operant conditioning differ?', 'Classical conditioning occurs when two stimuli are repeatedly paired, such as Pavlov’s dog. Operant conditioning modifies behavior through reward or punishment (reinforcement).', 2),
    c('Learning', 'What does cognitivism focus on?', 'What is going on inside the mind, such as problem-solving and decision-making.', 2, ['definition']),
    c('Learning', 'What is information-processing theory?', 'A cognitive model comparing the brain to a computer: both process incoming information, store it, and retrieve it.', 2, ['definition']),
    c('Learning', 'What is constructivism?', 'Learners must actively build or construct knowledge and skills based on past experiences.', 2, ['definition']),
    c('Learning', 'What is social learning?', 'Learning by observing, imitating, and modeling the actions of others.', 2, ['definition']),
    c('Learning', 'What are the four stages of social learning?', 'Attention, Retention, Reproduction, Motivation.', 2, ['list']),
    c('Learning', 'What are perception and insight?', 'Perception gives meaning to information received through one or more bodily senses. Insight groups perceptions into meaningful wholes when something is understood.', 2),
    c('Learning', 'What affects perception? (G-STEP)', 'Goals and Values, Self-Concept, Time and Opportunity, Element of Threat, Physical Organism.', 2, ['mnemonic', 'list']),
    c('Learning', 'What are the characteristics of learning? (RAMP)', 'Result of Experience, Active Process, Multifaceted, Purposeful.', 2, ['mnemonic', 'list']),
    c('Learning', 'What are the phases of skill development? (CAAR)', 'Cognitive, Associative, Automatic Response.', 2, ['mnemonic', 'list']),
    c('Learning', 'What is a learning plateau?', 'Learning is rapid early in training but tends to slow down; that slowdown is a learning plateau.', 2, ['definition']),
    c('Learning', 'What are the laws of learning? (REEPIR)', 'Readiness, Effect, Exercise, Primacy, Intensity, Recency.', 2, ['mnemonic']),
    c('Learning', 'What learning-style continua does the PDF list?', 'Right brain/left brain (analytical/creative); holistic/serialistic (top-down/bottom-up); visual/auditory/kinesthetic/tactile (VAKT); and active/reflective, sensing/intuitive, visual/verbal, sequential/global.', 2, ['list']),
    c('Learning', 'What are the cognitive-domain levels? (RUAC)', 'Rote, Understanding, Application, Correlation.', 2, ['mnemonic', 'list']),
    c('Learning', 'What are the affective-domain levels?', 'Receiving (awareness), Responding (reacting), Valuing (accepting), Organization (rearranging), and Characterization (integrating).', 2, ['list']),
    c('Learning', 'What are the psychomotor-domain levels?', 'Observation (watching), Imitation (copying), Practice (gaining proficiency), and Habit (automation).', 2, ['list']),
    c('Learning', 'How do slips and mistakes differ?', 'Slips are errors of action. Mistakes are errors of thought.', 2),
    c('Learning', 'How can errors be reduced?', 'Learn and practice; take time; check for errors; use reminders such as checklists; develop routines such as SOPs; and raise awareness when rushed or fatigued.', 2, ['procedure']),
    c('Learning', 'What principles aid retention?', 'Praise stimulates remembering; association promotes recall; favorable attitudes aid retention; learning with all senses is most effective; and meaningful repetition aids recall.', 2, ['list']),
    c('Learning', 'Why do people forget?', 'Retrieval failure; fading from lack of use; interference from an overshadowing experience or similar learning; and repression or suppression of a bad memory.', 3, ['list']),
    c('Learning', 'How do repression and suppression differ?', 'Repression is unconscious. Suppression is conscious.', 3),
    c('Learning', 'What are positive and negative transfer of learning?', 'Positive transfer occurs when one learned skill aids another. Negative transfer occurs when a previously learned skill interferes with a new skill.', 3),
    c('Learning', 'What is scenario-based training (SBT)?', 'A type of problem-based learning that uses real-world scenarios to meet training objectives. The instructor acts as mentor and coach to foster ADM skills.', 3, ['definition']),

    c('Communication', 'What is communication?', 'The continuous, two-way exchange of information for conveying ideas or feelings.', 3, ['definition']),
    c('Communication', 'When does effective communication take place?', 'When receivers react with understanding and change their behavior accordingly.', 3),
    c('Communication', 'What are the basic elements of communication? (SSR)', 'Source, Symbols, Receiver.', 3, ['mnemonic']),
    c('Communication', 'What characterizes effective communicators?', 'They select symbols meaningful to the receiver, display a positive attitude, and use accurate, up-to-date, stimulating material.', 3, ['list']),
    c('Communication', 'What receiver characteristics should an instructor understand?', 'The receiver’s viewpoint and background, willingness to listen or learn, and past experiences and motivations.', 3, ['list']),
    c('Communication', 'What are the barriers to effective communication? (COIL)', 'Confusion between the symbol and the symbolized object; overuse of abstractions; interference from external factors; and lack of common experience.', 3, ['mnemonic']),
    c('Communication', 'What are the first two COIL barriers?', 'Confusion occurs because words and symbols do not mean the same thing to everyone. Overuse of abstractions fails to evoke the intended items in the listener’s mind; use concrete, specific words.', 3),
    c('Communication', 'What types of interference can break down communication?', 'Physiological, environmental, and psychological interference.', 3),
    c('Communication', 'Give examples of physiological, environmental, and psychological interference.', 'Physiological: hearing loss, injury, or physical illness.\nEnvironmental: unfamiliar noises, vibrations, or smells.\nPsychological: mistrust or lack of commitment to the communication process.', 3, ['examples']),
    c('Communication', 'What is the greatest barrier to communication?', 'Lack of common experience. Instructors cannot use the same dialogue with pilots of different experience levels.', 4),
    c('Communication', 'How is listening different from hearing?', 'Hearing is passive but constant. Listening is active: hearing with comprehension.', 3),
    c('Communication', 'What do effective listeners do? (LIQIR)', 'Take notes, maintain eye contact, listen for main ideas, guard against daydreaming, and listen to understand rather than refute.', 3, ['mnemonic']),
    c('Communication', 'What is instructional communication?', 'Communication used to inform listeners in the teaching-learning process; it requires an instructor to be knowledgeable and confident.', 3, ['definition']),
    c('Communication', 'How can an instructor improve instructional communication?', 'Speak about material known very well; share past examples to illustrate points; use questioning to check understanding and show interest; ask open-ended why/how questions rather than closed yes/no questions.', 3, ['procedure']),
    c('Communication', 'What is instructional enhancement?', 'The more knowledgeable an instructor is, the more confident, engaging, and productive they will be at conveying material.', 3),
    c('Communication', 'What professional-development and role-playing opportunities support instructional communication?', 'Seminars, professional organizations, and online courses support development. Role-playing lets instructor applicants teach colleagues as if they were learners.', 3),

    c('Teaching', 'What are the essential teaching skills? (PAMS)', 'People Skills, Assessment Skills, Management Skills, Subject-Matter Expertise.', 4, ['mnemonic']),
    c('Teaching', 'What are the seven preparation steps for a lesson?', 'Establish objectives; organize material logically; determine instructional aids; develop learning activities; plan assessment; create a realistic timeline; plan closure.', 4, ['procedure']),
    c('Teaching', 'How do performance-based and decision-based objectives differ?', 'Performance-based objectives describe precisely what must be done and how. Decision-based objectives promote critical thinking, such as risk management.', 4),
    c('Teaching', 'What are the components of a performance-based objective?', 'Description, Conditions, Criteria.', 4, ['list']),
    c('Teaching', 'What belongs in a lesson introduction?', 'Attention to grab interest, such as a story; motivation to create desire to learn; and an overview of what will be covered.', 4),
    c('Teaching', 'How should lesson main points be organized?', 'From past to present; simple to complex; known to unknown; and most frequently used to least frequently used.', 4, ['list']),
    c('Teaching', 'What does a lesson conclusion do?', 'Reviews main points, relates them to objectives, and links knowledge gained to future lessons.', 4),
    c('Teaching', 'What are the steps in the teaching process? (P-PAR)', 'Preparation, Presentation, Application, Review and Assessment.', 4, ['mnemonic']),
    c('Teaching', 'What training delivery methods are listed?', 'Lecture: illustrated talk, briefing, formal lecture, informal lecture, teaching lecture.\nDiscussion: guided discussion.\nElectronic learning: computer-assisted learning, simulation/role-playing, cooperative/group learning.\nAlso demonstration-performance and drill-and-practice.', 4, ['list']),
    c('Teaching', 'What are the seven guided-discussion question types?', 'Lead-Off, Follow-up, Overhead, Rhetorical, Direct, Reverse, Relay.', 4, ['list']),
    c('Teaching', 'What is problem-based learning (PBL), and what forms can it take?', 'A teaching strategy confronting learners with real-life problems. Forms include scenario-based training, collaborative problem-solving, and case studies.', 4),
    c('Teaching', 'What are the guidelines for using instructional aids?', 'Establish objectives; research and gather supporting materials; organize material logically; and decide which ideas should be supported with aids.', 4, ['procedure']),

    c('Assessment', 'What assessment types are listed?', 'Traditional (written) or authentic (scenario-based); formal (documented) or informal (casual); formative (ungraded review) or summative (periodic course-progress measurement); and norm-referenced or criterion-referenced.', 4, ['list']),
    c('Assessment', 'How do norm-referenced and criterion-referenced assessment differ?', 'Norm-referenced compares performance against other learners. Criterion-referenced compares performance to an established standard.', 5),
    c('Assessment', 'What is authentic assessment?', 'It focuses on real-world tasks in authentic settings, evaluates application and correlation learning, and is learner-centered—focusing more on learning than grading.', 4),
    c('Assessment', 'What is the purpose of a proper assessment?', 'It contributes to learning, reveals instruction quality, highlights strengths and weaknesses, and indicates whether learning objectives were met.', 5, ['list']),
    c('Assessment', 'What makes an effective assessment? (FAST COCO)', 'Flexible, Acceptable, Specific, Thoughtful, Comprehensive, Objective, Constructive, Organized.', 5, ['mnemonic']),
    c('Assessment', 'What characterizes traditional assessment?', 'It generally means written tests, evaluates rote and understanding learning, is instructor-centered, and uses a traditional grade such as 95%.', 5),
    c('Assessment', 'What makes a good written test? (DR COVU)', 'Discrimination, Reliability, Comprehensiveness, Objectivity, Validity, Usability.', 5, ['mnemonic']),
    c('Assessment', 'How do you choose an assessment method?', 'Determine level-of-learning objectives; list indicators or desired behavior samples; establish performance-based criteria; then develop criterion-referenced assessment items.', 5, ['procedure']),
    c('Assessment', 'What critique types are listed?', 'Instructor/learner, instructor-led, learner-led, small-group, another-learner, self, and written critique.', 5, ['list']),
    c('Assessment', 'What are objective and open-ended oral questions?', 'Objective questions have one correct answer, such as who, what, when, or where. Open-ended statements implicitly ask for completion, such as why or how.', 5),
    c('Assessment', 'What characterizes effective questions?', 'They center on one idea, present a challenge, apply to the subject, are brief/concise/clear, and fit the learner’s abilities and experience.', 5),
    c('Assessment', 'Which question types should an instructor avoid?', 'Yes/no, toss-up, puzzling, oversize, bewildering, trick, and irrelevant questions.', 5, ['list']),

    c('Planning', 'What makes a good scenario-based lesson?', 'It has clear objectives, appeals to the learner, incorporates many tasks, has more than one correct answer, avoids an obvious solution, uses local-environment nuances, and requires decisions.', 5, ['list']),
    c('Planning', 'What makes a flight scenario realistic?', 'A purpose or reason to go, and consequences if the mission is not completed.', 5),
    c('Planning', 'What are the scenario-development steps?', 'Identify preferably decision-based objectives; choose ground or flight format; devise a situation; incorporate tasks; include a problem; identify a trigger event; plan transitions; identify decision points and feedback/reflection areas; identify positive and negative outcomes.', 5, ['procedure']),
    c('Planning', 'What is the building-block concept?', 'New learning is based on existing knowledge and experience; learners progressively stack new knowledge and skills.', 6, ['definition']),
    c('Planning', 'How is the building-block concept implemented?', 'Determine training objectives; identify blocks of learning within them; arrange the blocks in a logical sequence.', 6, ['procedure']),
    c('Planning', 'What is the purpose of a training syllabus?', 'To ensure logical training sequence, act as a completion checklist, and help develop lesson plans.', 6),
    c('Planning', 'What is the purpose of a lesson plan?', 'Keep the instructor on track; give inexperienced instructors confidence; prevent missed important points; organize an efficient sequence; promote consistent instruction; and support recordkeeping.', 6),
    c('Planning', 'What makes a well-planned lesson? (FIRCUPS)', 'Flexibility, Instructional Steps, Relation to Course, Content, Unity, Practicality, Scope.', 6, ['mnemonic']),

    c('Professionalism', 'How do aviation instructors help learners learn?', 'Make learning enjoyable, beneficial, and interesting, and set measurable standards.', 6),
    c('Professionalism', 'What does providing adequate instruction require?', 'Tailored instruction, attention to slow and fast learners, awareness of errors, and instructor development.', 6),
    c('Professionalism', 'What does demanding performance standards involve?', 'Meeting minimal testing standards while striving for excellence.', 6),
    c('Professionalism', 'How should instructors emphasize the positive?', 'Recognize instructor influence; make first lessons enjoyable; introduce emergency procedures with care; and be flexible with instructional methods.', 6),
    c('Professionalism', 'How can instructors minimize learner frustrations? (MACK BAG)', 'Motivate learners; Approach them as individuals; Criticize constructively; Keep them informed; Be consistent; Admit errors; Give credit when due.', 6, ['mnemonic']),
    c('Professionalism', 'What is professionalism?', 'An attitude expressed only when a service is performed; based on study and research; demanding ethics; achieved after extended training/preparation; and requiring good judgment and logical reasoning.', 6, ['definition']),
    c('Professionalism', 'What are characteristics of professional instructors? (3 SAD P’s)', 'Sincerity, Acceptance, Demeanor, Personal Appearance, Personal Habits, Proper Language.', 6, ['mnemonic']),
    c('Professionalism', 'What does the Aviation Instructor’s Code of Conduct emphasize?', 'Safety first; good judgment; effective risk management; accountability; responsibility and courtesy; prudent operating practices; and applicable laws and regulations.', 6, ['list']),
    c('Professionalism', 'How should aviation instructors pursue professional development?', 'Avoid complacency through seminars, workshops, and WINGS; use reflective teaching; maintain a current library; expand qualifications; and participate in professional organizations for education, training, or networking.', 7, ['list']),
    c('Professionalism', 'How do instructors help ensure aviation safety?', 'They serve as role models, stay involved on an ongoing basis, and teach aeronautical decision-making and risk management.', 7),

    c('Flight instruction', 'What physiological obstacles are identified for flight instructors?', 'Unfamiliar environments and sensations, and motion sickness.', 7),
    c('Flight instruction', 'What does assessment of piloting ability determine?', 'How well a learner is progressing. A good assessment gives the learner something constructive on which to work or build.', 7),
    c('Flight instruction', 'What is required before endorsing a first solo?', 'The instructor must determine that the learner is qualified and proficient in all maneuvers and procedures required by 14 CFR 61.87, based on consistent proficiency demonstrations.', 7, ['regulation']),
    c('Flight instruction', 'What is demonstrated ability based on?', 'Established performance standards, suitably modified for the learner’s experience level and training stage.', 7),
    c('Flight instruction', 'How should instructors correct learner errors?', 'Do not immediately take over for every mistake. When safety permits, let learners progress partway into the error and find a way out.', 7),
    c('Flight instruction', 'How should flight instructors keep learners informed?', 'Update progress as procedures or maneuvers are completed, or summarize it during postflight critiques.', 7),
    c('Flight instruction', 'What responsibilities are identified for flight instructors?', 'Ensure learner skill set for solo flight; observe limits on solo authorization and solo privileges; administer presolo written exams; handle knowledge tests, practical-test recommendations, retesting after failure, and endorsement accountability; emphasize see-and-avoid and proper checklist use.', 7, ['list']),
    c('Flight instruction', 'What are the four demonstration-performance steps?', '1. Instructor explanations.\n2. Instructor demonstrations.\n3. Learner performance with instructor supervision.\n4. Instructor evaluation.', 7, ['procedure']),
    c('Flight instruction', 'What are the five telling-and-doing steps?', '1. Preparation (instructor explanations).\n2. Instructor tells—instructor does.\n3. Learner tells—instructor does.\n4. Learner tells—learner does.\n5. Learner does—instructor evaluates.', 7, ['procedure']),
    c('Flight instruction', 'What is the key difference between demonstration-performance and telling-and-doing?', 'Step three: in telling-and-doing, the learner tells while the instructor does.', 7),
    c('Flight instruction', 'What are the positive exchange-of-controls steps?', '“You have the flight controls.”\n“I have the flight controls.”\n“You have the flight controls.”', 7, ['procedure']),
    c('Flight instruction', 'What is the sterile cockpit rule?', '14 CFR 121.542 requires air-carrier pilots to refrain from nonessential activities during critical phases of flight. GA pilots can adopt it; for light aircraft, critical phases can be defined as below 2,500 feet AGL or within 10 minutes of landing.', 7, ['regulation']),
    c('Flight instruction', 'How can instructors use distractions in training?', 'Discuss an unrelated enjoyable topic; have the learner obtain weather via onboard electronics; identify terrain/objects; or identify a forced-landing field. Do not use distractions in initial learning of a new skill.', 7, ['procedure']),

    c('ADM and safety', 'What is aeronautical decision-making (ADM)?', 'A systematic approach to the mental process pilots use to consistently determine the best course of action in given circumstances.', 7, ['definition']),
    c('ADM and safety', 'How do analytical and automatic decision-making differ?', 'Analytical decision-making takes time to evaluate options; DECIDE is one model. Automatic/naturalistic decision-making demands a quick decision at the cost of accuracy and is typically used in emergencies.', 7),
    c('ADM and safety', 'What are the decision-making process steps?', '1. Define the problem.\n2. Choose a course of action.\n3. Implement the decision and evaluate the outcome.', 7, ['procedure']),
    c('ADM and safety', 'What is integrated flight instruction?', 'Teaching learners to perform maneuvers using both outside visual and inside instrument references from the first introduction of each maneuver.', 8, ['definition']),
    c('ADM and safety', 'What is the “see and avoid” attention guideline?', 'At least 90% of a pilot’s attention should be devoted to outside visual references and traffic scanning.', 8),
    c('ADM and safety', 'What are the five hazardous attitudes?', 'Anti-authority, Impulsivity, Invulnerability, Macho, Resignation.', 8, ['list'])
  ];

  const definedTerms = [
    // Acronym and named-term cards: separate only where the term itself has a definition to learn.
    c('Learning', 'What is memorization in the MUA model?', 'Memorizing facts.', 1),
    c('Learning', 'What is understanding in the MUA model?', 'Organizing facts and making similarities and associations.', 1),
    c('Learning', 'What is application in the MUA model?', 'Using knowledge to solve problems and make decisions.', 1),
    c('Learning', 'What is attention in social learning?', 'Observing others.', 2),
    c('Learning', 'What is retention in social learning?', 'Remembering an observed behavior.', 2),
    c('Learning', 'What is reproduction in social learning?', 'Producing an observed behavior.', 2),
    c('Learning', 'What is motivation in social learning?', 'Deciding to reproduce an observed behavior.', 2),
    c('Learning', 'What do goals and values mean in G-STEP?', 'Beliefs shape learning experiences.', 2),
    c('Learning', 'What does self-concept mean in G-STEP?', 'A favorable self-image makes a learner more receptive to new experiences.', 2),
    c('Learning', 'What does time and opportunity mean in G-STEP?', 'Learning takes time.', 2),
    c('Learning', 'What does element of threat mean in G-STEP?', 'Fear limits perceptiveness.', 2),
    c('Learning', 'What does physical organism mean in G-STEP?', 'The body affects the ability to detect and interpret information.', 2),
    c('Learning', 'What does result of experience mean in RAMP?', 'Learning is individual; an instructor cannot do it for the learner.', 2),
    c('Learning', 'What does active process mean in RAMP?', 'Knowledge is retained better when combined with hands-on activities.', 2),
    c('Learning', 'What does multifaceted mean in RAMP?', 'Learning can involve verbal, conceptual, perceptual, and problem-solving elements at once.', 2),
    c('Learning', 'What does purposeful mean in RAMP?', 'Everyone has specific intentions and goals.', 2),
    c('Learning', 'What is the cognitive phase of skill development?', 'Memorizing the required steps.', 2),
    c('Learning', 'What is the associative phase of skill development?', 'Coordinating muscles with visual and tactile senses through practice.', 2),
    c('Learning', 'What is the automatic-response phase of skill development?', 'Doing things simultaneously with rapid, smooth performance.', 2),
    c('Learning', 'What is readiness in REEPIR?', 'People learn best when physically, mentally, and emotionally ready.', 2),
    c('Learning', 'What is effect in REEPIR?', 'Learning is strengthened when associated with pleasant experiences.', 2),
    c('Learning', 'What is exercise in REEPIR?', 'Things repeated or practiced are best remembered.', 2),
    c('Learning', 'What is primacy in REEPIR?', 'Things learned first create strong impressions, so they must be taught right the first time.', 2),
    c('Learning', 'What is intensity in REEPIR?', 'Exciting learning experiences teach more than routine or dull experiences.', 2),
    c('Learning', 'What is recency in REEPIR?', 'Things most recently learned are best remembered.', 2),
    c('Learning', 'What is rote learning in RUAC?', 'Defining.', 2),
    c('Learning', 'What is understanding in RUAC?', 'Explaining.', 2),
    c('Learning', 'What is application in RUAC?', 'Solving.', 2),
    c('Learning', 'What is correlation in RUAC?', 'Comparing.', 2),
    c('Learning', 'What is sensory memory?', 'Memory that receives environmental information, processes it, and discards extraneous material.', 2),
    c('Learning', 'What is short-term memory?', 'Working or “scratch-pad” memory that stores information for roughly 30 seconds while it is used.', 2),
    c('Learning', 'What is long-term memory?', 'Relatively permanent storage of unlimited information.', 2),
    c('Learning', 'Why does praise stimulate remembering?', 'Responses that give a pleasurable return tend to be repeated.', 3),
    c('Learning', 'Why does association promote recall?', 'Information or actions associated with something to be learned tend to facilitate recall.', 3),
    c('Learning', 'Why do favorable attitudes aid retention?', 'Without motivation, there is little chance for recall.', 3),
    c('Learning', 'Why is learning with all senses most effective?', 'Using several senses together improves understanding and recall.', 3),
    c('Learning', 'Why does meaningful repetition aid recall?', 'Repetition improves perception; three or four repetitions provide the maximum effect.', 3),
    c('Learning', 'What is retrieval failure?', 'An inability to retrieve information, such as the tip-of-the-tongue phenomenon.', 3),
    c('Learning', 'What is fading as a reason people forget?', 'Information not used for an extended period fades away.', 3),
    c('Learning', 'What is interference as a reason people forget?', 'A particular experience overshadows information, or similar learning intervenes.', 3),
    c('Learning', 'What is repression or suppression as a reason people forget?', 'A bad memory is pushed out of reach; repression is unconscious and suppression is conscious.', 3),
    c('Learning', 'What is deliberate practice?', 'Practicing specific areas for improvement with brief instructor feedback.', 3),
    c('Learning', 'What is blocked practice?', 'Practicing the same drill until movement becomes automatic; it gives good short-term performance but poorer long-term learning.', 3),
    c('Learning', 'What is random practice?', 'Mixing practice skills in random order to recognize similarities and differences.', 3),
    c('Communication', 'What is the Source in SSR?', 'The sender, speaker, or writer.', 3),
    c('Communication', 'What are Symbols in SSR?', 'The words or gestures used.', 3),
    c('Communication', 'What is the Receiver in SSR?', 'The listener or reader.', 3),
    c('Communication', 'What is confusion between a symbol and its symbolized object?', 'A barrier caused when words and symbols do not represent the same thing to every person.', 3),
    c('Communication', 'What is overuse of abstractions?', 'A barrier where abstract words fail to evoke the item the communicator intends; concrete words should be used.', 3),
    c('Communication', 'What is interference in the communication cycle?', 'A breakdown caused by physiological, environmental, or psychological factors.', 3),
    c('Teaching', 'What are People Skills in PAMS?', 'Communicate clearly, motivate learners, and adapt to their needs.', 4),
    c('Teaching', 'What are Assessment Skills in PAMS?', 'Provide guidance, suggestions for improvement, and positive reinforcement.', 4),
    c('Teaching', 'What are Management Skills in PAMS?', 'Plan, organize, lead, and supervise.', 4),
    c('Teaching', 'What is Subject-Matter Expertise in PAMS?', 'Expertise in aviation and teaching.', 4),
    c('Teaching', 'What is Description in a performance-based objective?', 'An explanation of the skill or behavior to be learned.', 4),
    c('Teaching', 'What are Conditions in a performance-based objective?', 'The rules for performance, such as using no more than 5° of bank.', 4),
    c('Teaching', 'What are Criteria in a performance-based objective?', 'The standards for performance, such as within ±100 feet.', 4),
    c('Teaching', 'What is a lead-off guided-discussion question?', 'A question that opens discussion, usually beginning with how or why.', 4),
    c('Teaching', 'What is a follow-up guided-discussion question?', 'A question used to further guide the discussion.', 4),
    c('Teaching', 'What is an overhead guided-discussion question?', 'A question directed to the entire group.', 4),
    c('Teaching', 'What is a rhetorical guided-discussion question?', 'A question that spurs thought but is answered by the instructor.', 4),
    c('Teaching', 'What is a direct guided-discussion question?', 'A question asked to a specific individual.', 4),
    c('Teaching', 'What is a reverse guided-discussion question?', 'An instructor redirecting a learner’s question to another learner.', 4),
    c('Teaching', 'What is a relay guided-discussion question?', 'A reverse question redirected to the group instead of one learner.', 4),
    c('Assessment', 'How can authentic assessment use a rubric?', 'Use defined levels for grading, such as describe, explain, practice, and perform.', 5),
    c('Assessment', 'What is collaborative assessment?', 'An authentic postflight-debrief method using replay, reconstruct, reflect, and redirect.', 5),
    c('Assessment', 'What does Flexible mean in FAST COCO?', 'Fits the learner and the occasion.', 5),
    c('Assessment', 'What does Acceptable mean in FAST COCO?', 'The learner must first accept the instructor to accept the critique.', 5),
    c('Assessment', 'What does Specific mean in FAST COCO?', 'Guidance is clear and concise.', 5),
    c('Assessment', 'What does Thoughtful mean in FAST COCO?', 'It does not ridicule or anger the learner.', 5),
    c('Assessment', 'What does Comprehensive mean in FAST COCO?', 'It covers both strengths and weaknesses.', 5),
    c('Assessment', 'What does Objective mean in FAST COCO?', 'It does not reflect the instructor’s opinions or preferences.', 5),
    c('Assessment', 'What does Constructive mean in FAST COCO?', 'It benefits the learner.', 5),
    c('Assessment', 'What does Organized mean in FAST COCO?', 'It is logical and makes sense to the learner.', 5),
    c('Assessment', 'What does Discrimination mean in DR COVU?', 'Small differences can be measured between learners or course objectives.', 5),
    c('Assessment', 'What does Reliability mean in DR COVU?', 'It yields consistent results.', 5),
    c('Assessment', 'What does Comprehensiveness mean in DR COVU?', 'It samples a good cross-section of the knowledge measured.', 5),
    c('Assessment', 'What does Objectivity mean in DR COVU?', 'It can be graded consistently.', 5),
    c('Assessment', 'What does Validity mean in DR COVU?', 'It measures achievement of lesson objectives and nothing else.', 5),
    c('Assessment', 'What does Usability mean in DR COVU?', 'It is easy to give, read, and grade.', 5),
    c('Assessment', 'What is an instructor/learner critique?', 'A joint or group discussion.', 5),
    c('Assessment', 'What is an instructor-led critique?', 'An instructor critiques a learner’s performance.', 5),
    c('Assessment', 'What is a learner-led critique?', 'The learner leads the assessment.', 5),
    c('Assessment', 'What is a small-group critique?', 'Small groups analyze information and present their findings to the class.', 5),
    c('Assessment', 'What is a critique by another learner?', 'The instructor requires another learner to present a critique.', 5),
    c('Assessment', 'What is a self critique?', 'A learner critiques a personal performance.', 5),
    c('Assessment', 'What is a written critique?', 'Notes help the instructor recall details and give the learner a later reference.', 5),
    c('Assessment', 'Why avoid a yes-or-no question?', 'It requires only a short answer.', 5),
    c('Assessment', 'Why avoid a toss-up question?', 'It offers two viable options.', 5),
    c('Assessment', 'Why avoid a puzzling question?', 'It has many parts that must be assembled before it can be understood.', 5),
    c('Assessment', 'Why avoid an oversize question?', 'It is too broad.', 5),
    c('Assessment', 'Why avoid a bewildering question?', 'It is hard to read or understand.', 5),
    c('Assessment', 'Why avoid a trick question?', 'It is designed to be misleading.', 5),
    c('Assessment', 'Why avoid an irrelevant question?', 'It is unrelated to the learning objective.', 5),
    c('Planning', 'What does Flexibility mean in FIRCUPS?', 'Adaptable.', 6),
    c('Planning', 'What do Instructional Steps mean in FIRCUPS?', 'They fit the four steps of the teaching process.', 6),
    c('Planning', 'What does Relation to Course mean in FIRCUPS?', 'It clearly reflects the overall training goals.', 6),
    c('Planning', 'What does Content mean in FIRCUPS?', 'It contains new material and a review.', 6),
    c('Planning', 'What does Unity mean in FIRCUPS?', 'It has a limited number of connected objectives.', 6),
    c('Planning', 'What does Practicality mean in FIRCUPS?', 'It is planned for the situation.', 6),
    c('Planning', 'What does Scope mean in FIRCUPS?', 'It covers the right amount of material.', 6),
    c('Professionalism', 'What is Sincerity in 3 SAD P’s?', 'Genuineness.', 6),
    c('Professionalism', 'What is Acceptance in 3 SAD P’s?', 'Warmth.', 6),
    c('Professionalism', 'What is Demeanor in 3 SAD P’s?', 'Outward behavior.', 6),
    c('Professionalism', 'What is Personal Appearance in 3 SAD P’s?', 'Dress for success.', 6),
    c('Professionalism', 'What are Personal Habits in 3 SAD P’s?', 'Tendencies.', 6),
    c('Professionalism', 'What is Proper Language in 3 SAD P’s?', 'No profanity.', 6),
    c('ADM and safety', 'What is the antidote for anti-authority?', '“Follow the rules. They are usually right.”', 8),
    c('ADM and safety', 'What is the antidote for impulsivity?', '“Not so fast, think first.”', 8),
    c('ADM and safety', 'What is the antidote for invulnerability?', '“It could happen to me.”', 8),
    c('ADM and safety', 'What is the antidote for macho?', '“Taking chances is foolish.”', 8),
    c('ADM and safety', 'What is the antidote for resignation?', '“I’m not helpless. I can make a difference.”', 8)
  ];

  const seenIds = new Set();
  window.FOI_CARDS = [...baseCards, ...definedTerms].filter(card => {
    if (seenIds.has(card.id)) throw new Error(`Duplicate FOI card id: ${card.id}`);
    seenIds.add(card.id);
    return true;
  });
})();
